### ISSUE TITLE
Documentation d'installation

### ISSUE THREAD

**Issue by anthony-o** [lauregch/decodecodex#1]
Super projet !

Néanmoins, il serait peut-être bon d'indiquer dans le README comment se faire son propre Google Spreadsheet en utilisant ce script, en bref, une documentation d'installation.

**Comment by lauregch** [comment]
Tout à fait, c'était prévu, je vais ajouter ça rapidement, à mon sens c'est plutôt prioritaire par rapport au reste de la roadmap :)

**Comment by lauregch** [comment]
C'est fait 👍
